version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    cooldown: # applies only to version-updates (not security-updates)
      default-days: 10
      semver-minor-days: 14 # wait 14 days before applying minor updates
      semver-major-days: 28
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 10
  - package-ecosystem: uv
    directory: / # Updates pyproject.toml + uv.lock
    schedule:
      interval: weekly
    cooldown:
      default-days: 10
      semver-minor-days: 14
      semver-major-days: 28
